name       : libeconf
version    : 0.5.2
release    : 2
source     :
    - https://github.com/openSUSE/libeconf/archive/refs/tags/v0.5.2.tar.gz : c9aa04b7ef1c7312a6e045184d15465db1985abb4058cc4c562fd33c9876bb34
homepage   : https://opensuse.github.io/libeconf
license    : MIT
component  : system.base
summary    : Enhanced config file parser
description: |
    Enhanced config file parser, which merges config files placed in several locations into one
emul32     : yes
setup      : |
    %patch -p1 -i $pkgfiles/0001-Change-usr-etc-to-usr-share-defaults-etc.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
